common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/',  auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name = 'signup'),
]

dsl_app/urls.py
from django.urls import path, include
from dsl_app import views

app_name = 'dsl_app'

urlpatterns = [
    path('', views.index, name = 'index'),
    # path('register/', views.register)
]

dsl_restaurant_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dsl_app/', include('dsl_app.urls')),
    path('common/', include('common.urls')),
]

dsl_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    category_id = models.IntegerField(primary_key=True)
    category_details = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'category'

class Menu(models.Model):
    menu_name = models.CharField(max_length=50)
    price = models.IntegerField(blank=True, null=True)
    restaurant = models.ForeignKey('Restaurant', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'menu'


class Restaurant(models.Model):
    restaurant_id = models.AutoField(primary_key=True)
    restaurant_name = models.CharField(unique=True, max_length=20)
    category = models.ForeignKey(Category, models.DO_NOTHING)
    adrs = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'restaurant'


class Review(models.Model):
    review_id = models.AutoField(primary_key=True)
    rating = models.IntegerField()
    comment = models.CharField(max_length=1000, blank=True, null=True)
    image = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, models.DO_NOTHING)
    restaurant = models.ForeignKey(Restaurant, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'review'


class ReviewDetails(models.Model):
    tag = models.ForeignKey('Tag', models.DO_NOTHING)
    review = models.ForeignKey(Review, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'review_details'


class Tag(models.Model):
    tag_id = models.IntegerField(primary_key=True)
    tag_details = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'tag'


# class User(models.Model):
#     user_id = models.AutoField(primary_key=True)
#     name = models.CharField(max_length=20)
#     login_id = models.CharField(unique=True, max_length=20)
#     login_pw = models.CharField(max_length=10)
#     join_date = models.DateTimeField(blank=True, null=True)
#
#     class Meta:
#         managed = False
#         db_table = 'user'

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

def signup(request):
    if request.method == "POST":
        # 화면에서 입력한 데이터로 사용자를 생성함.
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            # form.cleaned_data.get: 폼의 입력값을 개별적으로 얻고 싶은 경우에 사용함.
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            # 신규 사용자를 생성한 후에 자동 로그인이 될 수 있도록
            # authenticate: 사용자 인증을 담당(사용자명과 비밀번호가 정확한지 검증)
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            # login: 로그인(사용자 세션을 생성)
            login(request, user)  # 로그인
            return redirect('dsl_app/')
    else:
        # 회원가입 화면을 보여줌.
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

# @login_required: 로그인이 필요한 함수
# request.user는 현재 로그인한 계정의 User 모델 객체

dsl_app/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
# from dsl_app.forms import UserForm
from django.utils import timezone

def index(request): # main page
    return render(request, 'dsl_app/main.html')

templates/common/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- DSL CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>DSL_DB_study</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "common/navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/common/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    <!--값이 누락되었거나 필드의 형식이 일치하지 않는 경우에 발생-->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/common/login.html
{% extends "common/base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "common/form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'dsl_app:index' %}">DSL 맛집 DB</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %} <!--현재 사용자가 로그인되어 있는지-->
                    <!--사용자가 로그인되어 있으면 로그아웃 링크를 보여줌.-->
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <!--로그아웃 상태이면 로그인 링크를 보여줌.-->
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/common/signup.html
{% extends "common/base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "common/form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/dsl_app/main.html
{% extends 'common/base.html' %}
{% block content %}

<h1><div style="text-align:center">DSL 맛집 DB</div></h1>

{% endblock %}